---
- name: Install ROS Noetic on Ubuntu 20.04
  hosts: local
  become: false
  tasks:

   - name: Ensure python3-apt is installed
     apt:
       name: python3-apt
       state: present

       
    - name: Install ROS build tools
      apt:
        name:ros-noetic-ros-base 
        state: present
